"""Change created_at timestamp to timezone naive instead of aware

Revision ID: 45de4587b711
Revises: d1012bd037ec
Create Date: 2025-06-04 19:37:34.561815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = '45de4587b711'
down_revision: Union[str, None] = 'd1012bd037ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
