"""change tag join table's exercise foreigneky to exercise_id (eid)

Revision ID: 745fb60934e4
Revises: 87a148decb4d
Create Date: 2025-06-03 00:41:47.061850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = '745fb60934e4'
down_revision: Union[str, None] = '87a148decb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop old constraints
    op.drop_constraint('exercise_tags_tag_id_fkey', 'exercise_tags', type_='foreignkey')
    op.drop_constraint('exercise_tags_exercise_slug_fkey', 'exercise_tags', type_='foreignkey')
    
    # Rename tag_id to tid
    op.alter_column('exercise_tags', 'tag_id', new_column_name='tid')
    
    # Add eid column (without default for now)
    op.add_column('exercise_tags', sa.Column('eid', sa.UUID(), nullable=True))
    
    # POPULATE eid with actual exercise IDs based on exercise_slug
    op.execute("""
        UPDATE exercise_tags 
        SET eid = exercises.eid 
        FROM exercises 
        WHERE exercise_tags.exercise_slug = exercises.exercise_slug
    """)
    
    # Now make eid NOT NULL and drop exercise_slug
    op.alter_column('exercise_tags', 'eid', nullable=False)
    op.drop_column('exercise_tags', 'exercise_slug')
    
    # Finally add the FK constraints
    op.create_foreign_key(None, 'exercise_tags', 'exercises', ['eid'], ['eid'])
    op.create_foreign_key(None, 'exercise_tags', 'tags', ['tid'], ['tid'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_tags', sa.Column('exercise_slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exercise_tags', sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercise_tags', type_='foreignkey')
    op.drop_constraint(None, 'exercise_tags', type_='foreignkey')
    op.create_foreign_key('exercise_tags_exercise_slug_fkey', 'exercise_tags', 'exercises', ['exercise_slug'], ['exercise_slug'])
    op.create_foreign_key('exercise_tags_tag_id_fkey', 'exercise_tags', 'tags', ['tag_id'], ['tid'])
    op.drop_column('exercise_tags', 'tid')
    op.drop_column('exercise_tags', 'eid')
    # ### end Alembic commands ###
