"""empty message

Revision ID: 87a148decb4d
Revises: edad8705a76d
Create Date: 2025-06-02 17:00:44.579149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = '87a148decb4d'
down_revision: Union[str, None] = 'edad8705a76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('eid', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.alter_column('exercises', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_primary_key('exercises_pkey', 'exercises', ['eid'])
    op.add_column('workout_logs', sa.Column('exercise_eid', sa.UUID(), nullable=False))
    op.drop_constraint('log_fingerprint', 'workout_logs', type_='unique')
    op.drop_constraint('workout_logs_exercise_slug_fkey', 'workout_logs', type_='foreignkey')
    op.create_unique_constraint('log_fingerprint', 'workout_logs', ['user_uid', 'exercise_eid', 'reps', 'weight', 'date_performed', 'updated_at'])
    op.create_foreign_key(None, 'workout_logs', 'exercises', ['exercise_eid'], ['eid'])
    op.drop_column('workout_logs', 'exercise_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('exercise_slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_logs', type_='foreignkey')
    op.create_foreign_key('workout_logs_exercise_slug_fkey', 'workout_logs', 'exercises', ['exercise_slug'], ['exercise_slug'])
    op.drop_constraint('log_fingerprint', 'workout_logs', type_='unique')
    op.create_unique_constraint('log_fingerprint', 'workout_logs', ['user_uid', 'exercise_slug', 'reps', 'weight', 'date_performed', 'updated_at'])
    op.drop_column('workout_logs', 'exercise_eid')
    op.alter_column('exercises', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('exercises', 'eid')
    # ### end Alembic commands ###
