"""Update user model

Revision ID: bf30e4059ac6
Revises: 45de4587b711
Create Date: 2025-08-26 15:58:26.829674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = 'bf30e4059ac6'
down_revision: Union[str, None] = '45de4587b711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    heightunit_enum = sa.Enum('CENTIMETERS', 'INCHES', name='heightunit')
    heightunit_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('birth_month', sa.Integer(), nullable=True))
    op.add_column('user_accounts', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('user_accounts', sa.Column('height_raw', sa.Float(), nullable=True))
    op.add_column('user_accounts', sa.Column('height_unit', heightunit_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'height_unit')
    op.drop_column('user_accounts', 'height_raw')
    op.drop_column('user_accounts', 'birth_year')
    op.drop_column('user_accounts', 'birth_month')
    # ### end Alembic commands ###
