"""reset  tables

Revision ID: edad8705a76d
Revises: 
Create Date: 2025-05-30 13:34:17.568736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = 'edad8705a76d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_tags', sa.Column('exercise_slug', sa.String(), nullable=False))
    op.drop_constraint('exercise_tags_exercise_id_fkey', 'exercise_tags', type_='foreignkey')
    op.drop_constraint('workout_logs_exercise_eid_fkey', 'workout_logs', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_tags', 'exercises', ['exercise_slug'], ['exercise_slug'])
    op.drop_column('exercise_tags', 'exercise_id')
    op.drop_column('exercises', 'eid')
    op.add_column('workout_logs', sa.Column('exercise_slug', sa.String(), nullable=False))
    op.drop_constraint('log_fingerprint', 'workout_logs', type_='unique')
    op.create_unique_constraint('log_fingerprint', 'workout_logs', ['user_uid', 'exercise_slug', 'reps', 'weight', 'date_performed', 'updated_at'])
    op.create_foreign_key(None, 'workout_logs', 'exercises', ['exercise_slug'], ['exercise_slug'])
    op.drop_column('workout_logs', 'exercise_eid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('exercise_eid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_logs', type_='foreignkey')
    op.create_foreign_key('workout_logs_exercise_eid_fkey', 'workout_logs', 'exercises', ['exercise_eid'], ['eid'])
    op.drop_constraint('log_fingerprint', 'workout_logs', type_='unique')
    op.create_unique_constraint('log_fingerprint', 'workout_logs', ['user_uid', 'exercise_eid', 'reps', 'weight', 'date_performed', 'updated_at'])
    op.drop_column('workout_logs', 'exercise_slug')
    op.add_column('exercises', sa.Column('eid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('exercise_tags', sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercise_tags', type_='foreignkey')
    op.create_foreign_key('exercise_tags_exercise_id_fkey', 'exercise_tags', 'exercises', ['exercise_id'], ['eid'])
    op.drop_column('exercise_tags', 'exercise_slug')
    # ### end Alembic commands ###
